### ISSUE TITLE
Get NullPointerException

### ISSUE THREAD

**Issue by KingWu** [crosswall/Android-Coverflow#10]
First of all, i initialize an empty list. After call web service, update the list and call notifyDataSetChanged.

Then drag to the third Fragment, will get this issue.

> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setElevation(float)' on a null object reference
>                                                        at android.support.v4.view.ViewCompatLollipop.setElevation(ViewCompatLollipop.java:45)
>                                                        at android.support.v4.view.ViewCompat$LollipopViewCompatImpl.setElevation(ViewCompat.java:1538)
>                                                        at android.support.v4.view.ViewCompat.setElevation(ViewCompat.java:2713)
>                                                        at me.crosswall.lib.coverflow.core.PagerContainer.onPageSelected(PagerContainer.java:126)
>                                                        at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1867)
>                                                        at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:625)
>                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:609)
>                                                        at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2181)

**Comment by akshuu** [comment]
Same here.  I am also getting the same error.

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setElevation(float)' on a null object reference
                                                                                   at android.support.v4.view.ViewCompatLollipop.setElevation(ViewCompatLollipop.java:45)
                                                                                   at android.support.v4.view.ViewCompat$LollipopViewCompatImpl.setElevation(ViewCompat.java:1599)
                                                                                   at android.support.v4.view.ViewCompat.setElevation(ViewCompat.java:2808)
                                                                                   at com.grp10.codepath.travelmemo.activities.TripActivity$5.run(TripActivity.java:275)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:158)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by vincent-paing** [comment]
I think this might be due to the fact that View is taking a while to draw. Can I know if the layout are resource heavy?

**Comment by westito** [comment]
+1

**Comment by westito** [comment]
Setting ViewPager offscreenPageLimit = pageCount solves the problem.

**Comment by BongJaeChoi** [comment]
+1
@westito it is not real solution.

**Comment by zokirbekov** [comment]
Did anyone find solution ?
